# Generated by Django 4.0.4 on 2022-05-17 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cro', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=20)),
                ('telefones', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=50)),
                ('insc_estadual', models.CharField(max_length=50)),
                ('insc_municipal', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('telefones', models.CharField(max_length=50)),
                ('contato', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fechamento',
            fields=[
                ('nota_de_servico', models.IntegerField(primary_key=True, serialize=False)),
                ('vencimento', models.DateField()),
                ('data_pagamento', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('elemento', models.CharField(blank=True, max_length=50, null=True)),
                ('entrada', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('saida_1a_prova', models.DateField(blank=True, null=True)),
                ('retorno_1a_prova', models.DateField(blank=True, null=True)),
                ('saida_2a_prova', models.DateField(blank=True, null=True)),
                ('retorno_2a_prova', models.DateField(blank=True, null=True)),
                ('entrega', models.DateField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.cliente')),
                ('fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notas.fechamento')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.servico')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.clinica'),
        ),
    ]
