# Generated by Django 4.0.4 on 2022-05-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_alter_clinica_contato_alter_clinica_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
