# Generated by Django 4.2.3 on 2023-08-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_trabalho_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='valor_unitario',
        ),
        migrations.AddField(
            model_name='servico',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=20),
            preserve_default=False,
        ),
    ]
