# Generated by Django 4.0.4 on 2022-05-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_alter_servico_id_alter_trabalho_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamento',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
