# Generated by Django 4.2.3 on 2023-08-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_remove_trabalho_valor_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='cor',
            field=models.CharField(default='Não informada', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='elemento',
            field=models.CharField(default='Não informado', max_length=50),
            preserve_default=False,
        ),
    ]
