# Generated by Django 4.0.4 on 2022-05-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_alter_fechamento_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamento',
            name='vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
