# Generated by Django 4.0.4 on 2022-05-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_alter_fechamento_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='contato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contato_da_clinica', to='notas.cliente'),
        ),
    ]
