# Generated by Django 4.0.4 on 2022-05-20 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_alter_clinica_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica_Dentista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='clinica',
        ),
        migrations.AddField(
            model_name='cliente',
            name='clinica',
            field=models.ManyToManyField(related_name='clinicadentista', through='notas.Clinica_Dentista', to='notas.clinica'),
        ),
        migrations.AddField(
            model_name='clinica_dentista',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.cliente'),
        ),
        migrations.AddField(
            model_name='clinica_dentista',
            name='clinica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.clinica'),
        ),
    ]
