# Generated by Django 4.0.4 on 2022-05-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0007_clinica_dentista_remove_cliente_clinica_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinica_dentista',
            options={'verbose_name': 'Relação Dentista-Clínica', 'verbose_name_plural': 'Relações Dentista-Clínica'},
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='clinica',
        ),
        migrations.AddField(
            model_name='cliente',
            name='clinicas',
            field=models.ManyToManyField(through='notas.Clinica_Dentista', to='notas.clinica'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='clientes',
            field=models.ManyToManyField(through='notas.Clinica_Dentista', to='notas.cliente'),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='retorno_3a_prova',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabalho',
            name='saida_3a_prova',
            field=models.DateField(blank=True, null=True),
        ),
    ]
