# Generated by Django 4.2.3 on 2023-08-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0007_trabalho_desconto_trabalho_taxa_urgencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=999999, max_digits=20),
        ),
    ]
